name: Update Submodule

on:
  repository_dispatch:
    types: [update-content]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Update submodule
        run: |
          git submodule update --remote --merge notesneo-content
          
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add notesneo-content
            git commit -m "chore: update notesneo-content to latest"
            git push
          else
            echo "No changes to commit"
          fi
